export const configFileName = "transform.config.js";

export const defaultConfig = {
  entry: "/api/entry",
  output: "/api/output",
};
export const defaultConfigTmp = `
module.exports = ${JSON.stringify(defaultConfig, null, 4)}`;

export const entryFileTmp = ` 
module.exports = {
  example:{
      data:[
          {
              id:1,
              name:'test'
          }
      ]
  }
}`;

export const outputFileTmp = (namespaceName, value) => {
  `
  /* eslint-disable */

  /* This file generated by transform-type, do not modify it!!! */

  /* prettier-ignore-start */
  // @ts-ignore
  export namespace ${namespaceName}{
      ${value}
  }
  /* prettier-ignore-end */
  `;
};

export const defaultPrettierConfig = {
  parser: "typescript",
  trailingComma: "all",
  printWidth: 100,
  arrowParens: "always",
  jsxBracketSameLine: false,
  endOfLine: "lf",
  proseWrap: "always",
};
export const JSTTOptions = {
  bannerComment: "",
  style: defaultPrettierConfig,
};
